# SKLearn 06 | Regression dengan KNN | K-Nearest Neighbours

KKN dapat digunakan untuk melakukan prediksi berdasarkan karakteristik dengan sejumlah tetangga terdekat dan dapat diterapkan pada classification maupun regression tasks

# Sample data set

In [1]:
import pandas as pd

sensus = {'tinggi' : [ 158 , 170 , 183 , 191 , 155 , 163 , 180 , 158 , 170 ],
         'jk':[ 'pria' , 'pria' , 'pria' , 'pria' , 'wanita' , 'wanita' , 'wanita' , 'wanita' , 'wanita' ],
         'berat':[ 64 , 86 , 84 , 80 , 49 , 59 , 67 , 54 , 67 ]}
sensus_df = pd.DataFrame(sensus)
sensus_df

tinggi      jk  berat
0     158    pria     64
1     170    pria     86
2     183    pria     84
3     191    pria     80
4     155  wanita     49
5     163  wanita     59
6     180  wanita     67
7     158  wanita     54
8     170  wanita     67

# Features dan Target

sebelumnya kita harus mengelompokkan nilai features dan ni;ai target

In [2]:
import numpy as np
X_train = np.array(sensus_df[['tinggi','jk']])
y_train = np.array(sensus_df['berat'])

print(f'X_train : {X_train}')
print(f'y_train : {y_train}')

X_train : [[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [170 'wanita']]
y_train : [64 86 84 80 49 59 67 54 67]


# Preprocess Dataset : Konversi label menjadi numerik biner

pertama membuat tranpos dari data terlebih dahulu

In [3]:
X_train_transposed = np.transpose(X_train)
print(f'X_train : {X_train}')
print(f'X_train_transposed : {X_train_transposed}')

X_train : [[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [170 'wanita']]
X_train_transposed : [[158 170 183 191 155 163 180 158 170]
 ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita'
  'wanita']]


In [4]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
jk_binarised = lb.fit_transform(X_train_transposed[1])

print(f'jk : {X_train_transposed[1]}')
print(f'jk_binarised : {jk_binarised}')

jk : ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita' 'wanita']
jk_binarised : [[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [5]:
jk_binarised = jk_binarised.flatten()
jk_binarised

array([0, 0, 0, 0, 1, 1, 1, 1, 1])

In [6]:
X_train_transposed[1] = jk_binarised
X_train = X_train_transposed.transpose()

print(f'X_train_transposed : {X_train_transposed}')
print(f'X_train : {X_train}')

X_train_transposed : [[158 170 183 191 155 163 180 158 170]
 [0 0 0 0 1 1 1 1 1]]
X_train : [[158 0]
 [170 0]
 [183 0]
 [191 0]
 [155 1]
 [163 1]
 [180 1]
 [158 1]
 [170 1]]


# Training KNN Regression Model

Training model yang digunakan yaitu KNN 

In [7]:
from sklearn.neighbors import KNeighborsRegressor
K =3
model = KNeighborsRegressor(n_neighbors=K)
model.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=3)

setelah itu kita menggunakan model tersebut untuk memprediksi berat badan

In [8]:
X_new = np.array([155,1]).reshape(1,-1)
X_new

array([[155,   1]])

In [9]:
y_pred = model.predict(X_new)
y_pred

array([55.66666667])

# Evaluasi KNN Regression Model

membuat testing set  dengan 4 data point dengan nilai features dan sejumlah nilai target 

In [10]:
X_test = np.array([[ 168, 0 ],[ 180 , 0 ],[ 160 , 1 ],[ 169 , 1 ]])
y_test = np.array([ 65 , 96 , 52 , 67 ])
print(f'X_test : {X_test}')
print(f'y_test : {y_test}')

X_test : [[168   0]
 [180   0]
 [160   1]
 [169   1]]
y_test : [65 96 52 67]


In [11]:
y_pred = model.predict(X_test)
y_pred

array([70.66666667, 79.        , 59.        , 70.66666667])

# Coefficient of Determination

In [12]:
from sklearn.metrics import r2_score
r_squared = r2_score(y_test,y_pred)
print(f'R_Squared : {r_squared}')

R_Squared : 0.6290565226735438


# Mean Absolute Error (MAE)

In [13]:
from sklearn.metrics import mean_absolute_error
MAE = mean_absolute_error(y_test,y_pred)
print(f'MAE : {MAE}')

MAE : 8.333333333333336


# Mean Squared Error (MSE)

In [14]:
from sklearn.metrics import mean_squared_error
MSE = mean_squared_error(y_test,y_pred)
print(f'MSE : {MSE}')

MSE : 95.8888888888889


# Permasalahan Scalling pada Features

In [15]:
#tinggi dalam milimeter
from scipy.spatial.distance import euclidean
X_train = np.array([[1700,0],[1600,1]])
X_new = np.array([[1640,0]])
[euclidean(X_new[0],d)for d in X_train]

[60.0, 40.01249804748511]

In [16]:
#tinggi dalam meter
X_train = np.array([[1.7,0],[1.6,1]])
X_new = np.array([[1.64,0]])
[euclidean(X_new[0],d)for d in X_train]

[0.06000000000000005, 1.0007996802557444]

# Menerapkan Standard Scaler (Standard Score atau z-score)

In [17]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

In [18]:
#tinggi dalam milimeter
X_train = np.array([[1700,1],[1600,1]])
X_train_scaled = ss.fit_transform(X_train)
print(f'X_train_scaled : {X_train_scaled}')

X_new = np.array([[1640,0]])
X_new_scaled = ss.transform(X_new)
print(f'X_new_scaled : {X_new_scaled}')

jarak = [euclidean(X_new_scaled[0],d) for d in X_train_scaled]
print(f'Jarak : {jarak}')

X_train_scaled : [[ 1.  0.]
 [-1.  0.]]
X_new_scaled : [[-0.2 -1. ]]
Jarak : [1.562049935181331, 1.2806248474865698]


In [19]:
#tinggi dalam meter
X_train = np.array([[1.7,1],[1.6,1]])
X_train_scaled = ss.fit_transform(X_train)
print(f'X_train_scaled : {X_train_scaled}')

X_new = np.array([[1.64,0]])
X_new_scaled = ss.transform(X_new)
print(f'X_new_scaled : {X_new_scaled}')

jarak = [euclidean(X_new_scaled[0],d) for d in X_train_scaled]
print(f'Jarak : {jarak}')

X_train_scaled : [[ 1.  0.]
 [-1.  0.]]
X_new_scaled : [[-0.2 -1. ]]
Jarak : [1.5620499351813328, 1.280624847486568]


# Menerapkan Features Scaling pada KNN

# Dataset

In [20]:
#training set
X_train = np.array([[158,0],[170,0],[183,0],[191,0],[155,1],[163,1],[180,1],[158,1],[170,1]])
y_train = np.array([64,86,84,80,49,59,67,54,67])

#test set
X_test = np.array([[168,0],[180,0],[160,1],[169,1]])
y_test = np.array([[65,96,52,67]])

# Features Scalling (Standard Scaler)

In [21]:
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

print(f'X_train_scaled :{X_train_scaled}')
print(f'X_test_scaled : {X_test_scaled}')

X_train_scaled :[[-0.9908706  -1.11803399]
 [ 0.01869567 -1.11803399]
 [ 1.11239246 -1.11803399]
 [ 1.78543664 -1.11803399]
 [-1.24326216  0.89442719]
 [-0.57021798  0.89442719]
 [ 0.86000089  0.89442719]
 [-0.9908706   0.89442719]
 [ 0.01869567  0.89442719]]
X_test_scaled : [[-0.14956537 -1.11803399]
 [ 0.86000089 -1.11803399]
 [-0.82260955  0.89442719]
 [-0.06543485  0.89442719]]


# Training dan Evaluasi Model

In [22]:
model.fit(X_train_scaled,y_train)
y_pred = model.predict(X_test_scaled)

y_test_transpose = y_test.transpose()
MAE = mean_absolute_error(y_test_transpose, y_pred)
print(f'MAE : {MAE}')
MSE = mean_squared_error(y_test_transpose,y_pred)
print(f'MSE : {MSE}')

MAE : 7.583333333333336
MSE : 85.13888888888893
